export enum RoleName {
  ADMIN = 'ADMIN',
  FIELD_OFFICER = 'FIELD_OFFICER',
  ACCOUNTS = 'ACCOUNTS',
  VIEWER = 'VIEWER',
  BENEFICIARY = 'BENEFICIARY',
}

export enum LocationDirection {
  NORTH = 'NORTH',
  SOUTH = 'SOUTH',
  EAST = 'EAST',
  WEST = 'WEST',
}

export enum BeneficiaryStatus {
  ACTIVE = 'ACTIVE',
  INACTIVE = 'INACTIVE',
}

export enum LandStatus {
  ACTIVE = 'ACTIVE',
  INACTIVE = 'INACTIVE',
}

export enum ProjectStatus {
  PLANNING = 'PLANNING',
  ACTIVE = 'ACTIVE',
  SUSPENDED = 'SUSPENDED',
  COMPLETED = 'COMPLETED',
}

export enum ApplicationStatus {
  SUBMITTED = 'SUBMITTED',
  UNDER_REVIEW = 'UNDER_REVIEW',
  APPROVED = 'APPROVED',
  REJECTED = 'REJECTED',
}

export enum ApprovalStatus {
  APPROVED = 'APPROVED',
  REJECTED = 'REJECTED',
  CANCELLED = 'CANCELLED',
}

export enum BillStatus {
  PENDING = 'PENDING',
  PARTIALLY_PAID = 'PARTIALLY_PAID',
  PAID = 'PAID',
  CANCELLED = 'CANCELLED',
}

export enum InstallmentStatus {
  PENDING = 'PENDING',
  PARTIALLY_PAID = 'PARTIALLY_PAID',
  PAID = 'PAID',
  OVERDUE = 'OVERDUE',
  WAIVED = 'WAIVED',
  CANCELLED = 'CANCELLED',
}

export enum PaymentMode {
  CASH = 'CASH',
  BANK_TRANSFER = 'BANK_TRANSFER',
  UPI = 'UPI',
  CHEQUE = 'CHEQUE',
  DD = 'DD',
  ONLINE = 'ONLINE',
  OTHER = 'OTHER',
}

export enum PaymentStatus {
  COMPLETED = 'COMPLETED',
  REVERSED = 'REVERSED',
}

export enum InfrastructureStatus {
  PLANNED = 'PLANNED',
  UNDER_CONSTRUCTION = 'UNDER_CONSTRUCTION',
  COMPLETED = 'COMPLETED',
  COMMISSIONED = 'COMMISSIONED',
}

export enum ExtensionStatus {
  REQUESTED = 'REQUESTED',
  APPROVED = 'APPROVED',
  REJECTED = 'REJECTED',
  CANCELLED = 'CANCELLED',
}

export enum AuditAction {
  CREATE = 'CREATE',
  UPDATE = 'UPDATE',
  DELETE_VOID = 'DELETE_VOID',
  SUBMIT = 'SUBMIT',
  APPROVE = 'APPROVE',
  REJECT = 'REJECT',
  PARTIALLY_APPROVE = 'PARTIALLY_APPROVE',
  PAYMENT_RECORDED = 'PAYMENT_RECORDED',
  PAYMENT_REVERSED = 'PAYMENT_REVERSED',
  RATE_CHANGED = 'RATE_CHANGED',
  INSTALLMENT_SCHEDULE_CHANGED = 'INSTALLMENT_SCHEDULE_CHANGED',
  INFRASTRUCTURE_STATUS_CHANGED = 'INFRASTRUCTURE_STATUS_CHANGED',
  EXTENSION_APPROVED = 'EXTENSION_APPROVED',
}

export enum DocumentCategory {
  LAND_RECORD = 'LAND_RECORD',
  WATER_APPLICATION = 'WATER_APPLICATION',
  APPROVAL_LETTER = 'APPROVAL_LETTER',
  PAYMENT_RECEIPT = 'PAYMENT_RECEIPT',
  INFRASTRUCTURE_REPORT = 'INFRASTRUCTURE_REPORT',
  EXTENSION_REQUEST = 'EXTENSION_REQUEST',
  OTHER = 'OTHER',
}

export enum LocationImportStatus {
  UPLOADED = 'UPLOADED',
  VALIDATING = 'VALIDATING',
  VALIDATED = 'VALIDATED',
  IMPORTED = 'IMPORTED',
  FAILED = 'FAILED',
  CANCELLED = 'CANCELLED',
}
