export enum RoleName {
  ADMIN = 'ADMIN',
  FIELD_OFFICER = 'FIELD_OFFICER',
  COLLECTION_AGENT = 'COLLECTION_AGENT',
  ACCOUNTS = 'ACCOUNTS',
  VIEWER = 'VIEWER',
  BENEFICIARY = 'BENEFICIARY',
}

export enum UserStatus {
  ACTIVE = 'ACTIVE',
  LOCKED = 'LOCKED',
  DISABLED = 'DISABLED',
  ARCHIVED = 'ARCHIVED',
}

export enum DeviceStatus {
  ACTIVE = 'ACTIVE',
  REVOKED = 'REVOKED',
  BLOCKED = 'BLOCKED',
}

export enum PermissionCode {
  BENEFICIARY_VIEW = 'BENEFICIARY_VIEW',
  BENEFICIARY_CREATE = 'BENEFICIARY_CREATE',
  BENEFICIARY_EDIT = 'BENEFICIARY_EDIT',
  LAND_VIEW = 'LAND_VIEW',
  LAND_CREATE = 'LAND_CREATE',
  LAND_EDIT = 'LAND_EDIT',
  WATER_APPLICATION_VIEW = 'WATER_APPLICATION_VIEW',
  WATER_APPLICATION_CREATE = 'WATER_APPLICATION_CREATE',
  WATER_APPLICATION_APPROVE = 'WATER_APPLICATION_APPROVE',
  USAGE_VIEW = 'USAGE_VIEW',
  USAGE_RECORD = 'USAGE_RECORD',
  BILL_VIEW = 'BILL_VIEW',
  BILL_CREATE = 'BILL_CREATE',
  PAYMENT_VIEW = 'PAYMENT_VIEW',
  PAYMENT_RECORD = 'PAYMENT_RECORD',
  PAYMENT_REVERSE = 'PAYMENT_REVERSE',
  REPORT_VIEW = 'REPORT_VIEW',
  REPORT_EXPORT = 'REPORT_EXPORT',
  USER_VIEW = 'USER_VIEW',
  USER_CREATE = 'USER_CREATE',
  USER_EDIT = 'USER_EDIT',
  USER_DISABLE = 'USER_DISABLE',
  AUDIT_VIEW = 'AUDIT_VIEW',
  MASTER_DATA_MANAGE = 'MASTER_DATA_MANAGE',
  DEVICE_MANAGE = 'DEVICE_MANAGE',
  SYSTEM_ADMIN = 'SYSTEM_ADMIN',
}

export enum LocationDirection {
  NORTH = 'NORTH',
  SOUTH = 'SOUTH',
  EAST = 'EAST',
  WEST = 'WEST',
}

export enum BeneficiaryStatus {
  ACTIVE = 'ACTIVE',
  INACTIVE = 'INACTIVE',
}

export enum LandStatus {
  ACTIVE = 'ACTIVE',
  INACTIVE = 'INACTIVE',
}

export enum ProjectStatus {
  PLANNING = 'PLANNING',
  ACTIVE = 'ACTIVE',
  SUSPENDED = 'SUSPENDED',
  COMPLETED = 'COMPLETED',
}

export enum ApplicationStatus {
  SUBMITTED = 'SUBMITTED',
  UNDER_REVIEW = 'UNDER_REVIEW',
  APPROVED = 'APPROVED',
  REJECTED = 'REJECTED',
  CANCELLED = 'CANCELLED',
  VOIDED = 'VOIDED',
}

export enum ApprovalStatus {
  APPROVED = 'APPROVED',
  REJECTED = 'REJECTED',
  CANCELLED = 'CANCELLED',
}

export enum BillStatus {
  PENDING = 'PENDING',
  PARTIALLY_PAID = 'PARTIALLY_PAID',
  PAID = 'PAID',
  CANCELLED = 'CANCELLED',
}

export enum InstallmentStatus {
  PENDING = 'PENDING',
  PARTIALLY_PAID = 'PARTIALLY_PAID',
  PAID = 'PAID',
  OVERDUE = 'OVERDUE',
  WAIVED = 'WAIVED',
  CANCELLED = 'CANCELLED',
}

export enum PaymentMode {
  CASH = 'CASH',
  BANK_TRANSFER = 'BANK_TRANSFER',
  UPI = 'UPI',
  CHEQUE = 'CHEQUE',
  DD = 'DD',
  ONLINE = 'ONLINE',
  OTHER = 'OTHER',
}

export enum PaymentStatus {
  COMPLETED = 'COMPLETED',
  REVERSED = 'REVERSED',
}

export enum InfrastructureStatus {
  PLANNED = 'PLANNED',
  UNDER_CONSTRUCTION = 'UNDER_CONSTRUCTION',
  COMPLETED = 'COMPLETED',
  COMMISSIONED = 'COMMISSIONED',
}

export enum ExtensionStatus {
  DRAFT = 'DRAFT',
  REQUESTED = 'REQUESTED',
  UNDER_REVIEW = 'UNDER_REVIEW',
  APPROVED = 'APPROVED',
  PAYMENT_PENDING = 'PAYMENT_PENDING',
  PAID = 'PAID',
  ACTIVE = 'ACTIVE',
  REJECTED = 'REJECTED',
  CANCELLED = 'CANCELLED',
}

export enum ExtensionType {
  ADDITIONAL_LAND = 'ADDITIONAL_LAND',
  ADDITIONAL_WATER = 'ADDITIONAL_WATER',
  LAND_AND_WATER = 'LAND_AND_WATER',
  LATE_BENEFICIARY = 'LATE_BENEFICIARY',
}

export enum PaymentPurpose {
  ORIGINAL_DEVELOPMENT = 'ORIGINAL_DEVELOPMENT',
  EXTENSION_DEVELOPMENT = 'EXTENSION_DEVELOPMENT',
  RUNNING_WATER = 'RUNNING_WATER',
  OTHER = 'OTHER',
}

export enum AuditAction {
  CREATE = 'CREATE',
  UPDATE = 'UPDATE',
  DELETE_VOID = 'DELETE_VOID',
  SUBMIT = 'SUBMIT',
  APPROVE = 'APPROVE',
  REJECT = 'REJECT',
  PARTIALLY_APPROVE = 'PARTIALLY_APPROVE',
  PAYMENT_RECORDED = 'PAYMENT_RECORDED',
  PAYMENT_REVERSED = 'PAYMENT_REVERSED',
  RATE_CHANGED = 'RATE_CHANGED',
  INSTALLMENT_SCHEDULE_CHANGED = 'INSTALLMENT_SCHEDULE_CHANGED',
  INFRASTRUCTURE_STATUS_CHANGED = 'INFRASTRUCTURE_STATUS_CHANGED',
  EXTENSION_APPROVED = 'EXTENSION_APPROVED',
  USAGE_RECORDED = 'USAGE_RECORDED',
  USAGE_UPDATED = 'USAGE_UPDATED',
  USAGE_VERIFIED = 'USAGE_VERIFIED',
  USAGE_CORRECTED = 'USAGE_CORRECTED',
  USAGE_VOIDED = 'USAGE_VOIDED',
  RUNNING_BILL_CREATED = 'RUNNING_BILL_CREATED',
  RUNNING_BILL_VOIDED = 'RUNNING_BILL_VOIDED',
  RUNNING_PAYMENT_RECORDED = 'RUNNING_PAYMENT_RECORDED',
  RUNNING_PAYMENT_REVERSED = 'RUNNING_PAYMENT_REVERSED',
  TARIFF_RESOLVED = 'TARIFF_RESOLVED',
  COMMISSIONING_CHANGED = 'COMMISSIONING_CHANGED',
  RUNNING_START_DATE_CHANGED = 'RUNNING_START_DATE_CHANGED',
  SYSTEM_CLOCK_ROLLBACK = 'SYSTEM_CLOCK_ROLLBACK',
}

export enum BillingPeriodStatus {
  UPCOMING = 'UPCOMING',
  OPEN = 'OPEN',
  CLOSED = 'CLOSED',
}

export enum UsageEntryMode {
  DIRECT = 'DIRECT',
  METER_READING = 'METER_READING',
}

export enum WaterUsageStatus {
  DRAFT = 'DRAFT',
  RECORDED = 'RECORDED',
  SUBMITTED = 'SUBMITTED',
  VERIFIED = 'VERIFIED',
  BILLED = 'BILLED',
  VOIDED = 'VOIDED',
  OVER_ALLOCATION = 'OVER_ALLOCATION',
  REQUIRES_REVIEW = 'REQUIRES_REVIEW',
}

export enum DocumentCategory {
  LAND_RECORD = 'LAND_RECORD',
  WATER_APPLICATION = 'WATER_APPLICATION',
  APPROVAL_LETTER = 'APPROVAL_LETTER',
  PAYMENT_RECEIPT = 'PAYMENT_RECEIPT',
  INFRASTRUCTURE_REPORT = 'INFRASTRUCTURE_REPORT',
  EXTENSION_REQUEST = 'EXTENSION_REQUEST',
  OTHER = 'OTHER',
}

export enum LocationImportStatus {
  UPLOADED = 'UPLOADED',
  VALIDATING = 'VALIDATING',
  VALIDATED = 'VALIDATED',
  IMPORTED = 'IMPORTED',
  FAILED = 'FAILED',
  CANCELLED = 'CANCELLED',
}

export enum AuditEntityType {
  BENEFICIARY = 'Beneficiary',
  LAND_HOLDING = 'LandHolding',
  LAND_PARCEL = 'LandParcel',
  WATER_APPLICATION = 'WaterApplication',
  WATER_ALLOTMENT = 'WaterAllotment',
  DEVELOPMENT_BILL = 'DevelopmentBill',
  INSTALLMENT = 'Installment',
  INSTALLMENT_TEMPLATE = 'InstallmentTemplate',
  PAYMENT = 'Payment',
  INFRASTRUCTURE = 'Infrastructure',
  RUNNING_BILL = 'RunningBill',
  BILLING_PERIOD = 'BillingPeriod',
  WATER_USAGE_RECORD = 'WaterUsageRecord',
  SYSTEM_CLOCK = 'SystemClock',
  EXTENSION = 'Extension',
  RATE_CONFIGURATION = 'RateConfiguration',
  USER_ACCOUNT = 'UserAccount',
  LOCATION_IMPORT = 'LocationImport',
  FIND_FILTER_QUERY = 'FindFilterQuery',
  REPORT_EXPORT = 'ReportExport',
  REPORT_PRESET = 'ReportPreset',
  SYSTEM_BACKUP = 'SystemBackup',
  SYSTEM_RESTORE = 'SystemRestore',
}

